# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.

In [1]:
import datetime
import requests
import json
import os

from dotenv import load_dotenv
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [8]:
def create_connection():
    """
    Створює підключення через SQLAlchemy
    """
    load_dotenv()

    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = "classicmodels"

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"


    engine = create_engine(
        connection_string,
        pool_size=2,          
        max_overflow=20,        
        pool_pre_ping=True,     
        echo=False              
    )
  
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")
        return None

engine = create_connection()

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3306/classicmodels
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3306/classicmodels)

## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [59]:
def customer_info_update (engine, customerNumber, new_phone=None, new_email=None):

    if new_phone is None and new_email is None:
        print("Немає даних для оновлення")
        return False
        
    check_query = text("""SELECT customerNumber, customerName FROM customers WHERE customerNumber = :customerNumber""")

    columns_query = text("""
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'customers'
    """)

    with engine.connect() as conn:
        result = conn.execute(check_query, {'customer_number': customer_number})
        customer = result.fetchone()

        if not customer:
            print(f"Клієнт {customer_number} не знайдений")
            return False

        print(f"👤 Оновлюємо клієнта: {customer[1]} (ID: {customer[0]})")

        columns_result = conn.execute(columns_query)
        columns = [row[0].lower() for row in columns_result.fetchall()]
        has_email_column = 'email' in columns

    with engine.connect() as conn:
        with conn.begin():
            try:
                if new_phone is not None:
                    update_phone_query = text("""
                        UPDATE customers
                        SET phone = :new_phone
                        WHERE customerNumber = :customerNumber
                    """)

                    conn.execute(update_phone_query, {
                        'new_phone': new_phone,
                        'customerNumber': customerNumber
                    })

                    print(f"Встановнений новий номер телефону: {new_phone}")

                if new_email is not None:
                    if has_email_column:
                        update_email_query = text("""
                            UPDATE customers
                            SET email = :new_email
                            WHERE customerNumber = :customerNumber
                        """)

                        conn.execute(update_email_query, {
                            'new_email': new_email,
                            'customerNumber': customerNumber
                        })

                        print(f"Встановлений новий email: {new_email}")
                    else:
                        print("Поле email у таблиці customers не існує")

                return True

            except Exception as e:
                print(f"Помилка: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False

In [60]:
check_customer = customer_info_update(
    engine,
    customerNumber=103,
    new_phone="0991234567",
    new_email="veronika@gmail.com"
)

Оновлюємо клієнта: Atelier graphique (ID: 103)
Встановнений новий номер телефону: 0991234567
Помилка: name 'has_email_column' is not defined
🔄 Всі зміни автоматично скасовано (ROLLBACK)

In [25]:
check_result_query = text("""
SELECT
    customerNumber,
    customerName,
    phone
FROM customers
WHERE customerNumber = :customerNumber
""")

df_result = pd.read_sql(
    check_result_query,
    engine,
    params={'customerNumber': 103}
)

print("Поточна контактна інформація клієнта:")
display(df_result)

Поточна контактна інформація клієнта:

   customerNumber       customerName       phone
0             103  Atelier graphique  0991234567

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [56]:
def create_new_order(engine, orderNumber, customerNumber, details):
    with engine.connect() as conn:
        with conn.begin():
            try:
                today = datetime.date.today()
                required_date = today + datetime.timedelta(days=7)

                conn.execute(text("""
                    INSERT INTO orders (orderNumber, orderDate, requiredDate, status, customerNumber)
                    VALUES (:orderNumber, :orderDate, :requiredDate, :status, :customerNumber)
                """), {
                    "orderNumber": orderNumber,
                    "orderDate": today,
                    "requiredDate": required_date,
                    "status": "In Process",
                    "customerNumber": customerNumber
                })

                print("Замовлення створено")

                for details_item in details:
                    # перевірка наявності
                    result = conn.execute(text("""
                        SELECT quantityInStock
                        FROM products
                        WHERE productCode = :productCode
                    """), {"productCode": details_item["productCode"]})

                    stock = result.fetchone()[0]

                    if stock < details_item["quantityOrdered"]:
                        raise Exception("Недостатньо товару")

                    # додавання в orderdetails
                    conn.execute(text("""
                        INSERT INTO orderdetails
                        (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                        VALUES
                        (:orderNumber, :productCode, :quantityOrdered, :priceEach, :orderLineNumber)
                    """), {
                        "orderNumber": orderNumber,
                        "productCode": details_item["productCode"],
                        "quantityOrdered": details_item["quantityOrdered"],
                        "priceEach": details_item["priceEach"],
                        "orderLineNumber": details_item["orderLineNumber"]
                    })

                    # зменшення складу
                    conn.execute(text("""
                        UPDATE products
                        SET quantityInStock = quantityInStock - :quantityOrdered
                        WHERE productCode = :productCode
                    """), {
                        "quantityOrdered": details_item["quantityOrdered"],
                        "productCode": details_item["productCode"]
                    })

                print("✅Все виконано успішно")
                return True

            except Exception as e:
                print("❌ Помилка:", e)
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False

In [57]:
details = [
    {
        "productCode": "S10_1678",
        "quantityOrdered": 5,
        "priceEach": 95.70,
        "orderLineNumber": 1
    }
]

check_new_order = create_new_order(engine, 7777777, 103, details)

Замовлення створено
✅Все виконано успішно

In [58]:
df_check = pd.read_sql("""
SELECT 
    o.orderNumber,
    o.orderDate,
    o.status,
    o.customerNumber,
    od.productCode,
    od.quantityOrdered,
    od.priceEach,
    p.quantityInStock
FROM orders o
JOIN orderdetails od ON o.orderNumber = od.orderNumber
JOIN products p ON od.productCode = p.productCode
WHERE o.orderNumber = 7777777
""", engine)

display(df_check)

,orderNumber,orderDate,status,customerNumber,productCode,quantityOrdered,priceEach,quantityInStock
0,7777777,2026-04-14,In Process,103,S10_1678,5,95.7,7913

In [55]:
# для перевірки створю ще хибне замовлення з неіснуючою кількістю товару, щоб перевірити інший сценарій функції

details = [
    {
        "productCode": "S10_1678",
        "quantityOrdered": 999999,  # явно більше ніж є
        "priceEach": 95.70,
        "orderLineNumber": 1
    }
]

check_new_order = create_new_order(engine, 17373737, 103, details)

Замовлення створено
❌ Помилка: Недостатньо товару
🔄 Всі зміни автоматично скасовано (ROLLBACK)